// browser-data.js — MetaChromatic Browser metadata
// Unified catalog of every browseable artifact across the Prism repo:
// scraped models, character entities, datasets, memory shards, voice profiles,
// archetype templates, and relationship graphs.
// All copy is authored in the Prism voice (mythic / sci-fi / psychometric).

window.BROWSER_CATALOG = [
  // ── SCRAPED MODELS ────────────────────────────────────────────
  {
    id: 'mdl-bigfive-v7',
    kind: 'model', subkind: 'psychometric',
    name: 'OCEAN-7 Trait Lattice',
    tagline: 'Big-Five w/ shadow-trait extension',
    faction: 'Vanguard',
    status: 'active',
    confidence: 96,
    integrity: 98.4,
    rows: 1842300,
    params: '7.4M',
    size: '184 MB',
    scrape_source: 'mirror://psychnet/ocean.v7',
    scrape_date: '2026-04-22T11:24:00Z',
    last_sync: '2h ago',
    tags: ['Big Five', 'Shadow Traits', 'Cross-Cultural'],
    linked: 412,
    sigil: 'pentagon',
    palette: ['#9b5cff', '#00f0ff'],
    bars: [
      { l: 'Coverage', v: 96, c: 'purple' },
      { l: 'Drift', v: 12, c: 'amber' },
      { l: 'Uplift', v: 84, c: 'cyan' },
    ],
    summary: 'A seven-axis personality lattice extending OCEAN with shadow-traits sourced from clinical longitudinal records. Used as the trunk for character archetype synthesis.',
    spark: [82, 84, 83, 87, 89, 91, 92, 91, 93, 94, 96],
  },
  {
    id: 'mdl-voice-resonance',
    kind: 'model', subkind: 'voice',
    name: 'Resonance.fm',
    tagline: 'Vocal timbre + cadence embeddings',
    faction: 'Vanguard',
    status: 'active',
    confidence: 92,
    integrity: 97.1,
    rows: 612000,
    params: '2.1B',
    size: '4.2 GB',
    scrape_source: 'mirror://soundforge/resonance',
    scrape_date: '2026-04-26T08:11:00Z',
    last_sync: '38m ago',
    tags: ['Voice', 'Prosody', 'Audio'],
    linked: 318,
    sigil: 'wave',
    palette: ['#00f0ff', '#e040fb'],
    bars: [
      { l: 'Timbre', v: 91, c: 'cyan' },
      { l: 'Cadence', v: 88, c: 'purple' },
      { l: 'Affect', v: 79, c: 'magenta' },
    ],
    summary: 'Continuous embedding of vocal timbre, breath, and cadence. Powers character voice fingerprints during live roleplay sessions.',
    spark: [78, 80, 84, 82, 85, 87, 89, 88, 90, 92, 92],
  },
  {
    id: 'mdl-narrative-arc',
    kind: 'model', subkind: 'narrative',
    name: 'Arc-Engine v3',
    tagline: 'Story beat + tension forecaster',
    faction: 'Allies',
    status: 'active',
    confidence: 88,
    integrity: 94.6,
    rows: 904000,
    params: '11.2B',
    size: '22 GB',
    scrape_source: 'mirror://archive.fictionspace',
    scrape_date: '2026-04-19T16:08:00Z',
    last_sync: '5h ago',
    tags: ['Narrative', 'Tension', 'Beats'],
    linked: 287,
    sigil: 'arc',
    palette: ['#fbbf24', '#9b5cff'],
    bars: [
      { l: 'Plot Fit', v: 86, c: 'gold' },
      { l: 'Tension', v: 92, c: 'purple' },
      { l: 'Pace', v: 74, c: 'green' },
    ],
    summary: 'A fine-tuned narrative arc forecaster trained on 904k annotated story beats. Drives the Memory engine\'s tension graph.',
    spark: [70, 72, 74, 78, 80, 82, 85, 86, 88, 88, 88],
  },
  {
    id: 'mdl-relational',
    kind: 'model', subkind: 'graph',
    name: 'Bondweave',
    tagline: 'Inter-character relationship graph',
    faction: 'Vanguard',
    status: 'active',
    confidence: 93,
    integrity: 96.0,
    rows: 482000,
    params: '480M',
    size: '1.1 GB',
    scrape_source: 'derived://prism/relationships',
    scrape_date: '2026-04-25T22:40:00Z',
    last_sync: '14h ago',
    tags: ['Graph', 'Relationships', 'Affinity'],
    linked: 1024,
    sigil: 'graph',
    palette: ['#e040fb', '#00f0ff'],
    bars: [
      { l: 'Density', v: 84, c: 'magenta' },
      { l: 'Affinity', v: 91, c: 'cyan' },
      { l: 'Conflict', v: 36, c: 'red' },
    ],
    summary: 'Multi-edge social graph. Encodes trust, suspicion, affection, debt, and shared memory weight between every character pair.',
    spark: [80, 82, 84, 85, 87, 88, 90, 91, 92, 93, 93],
  },
  {
    id: 'mdl-affect-engine',
    kind: 'model', subkind: 'affect',
    name: 'AffectKernel',
    tagline: 'Real-time emotional state predictor',
    faction: 'Allies',
    status: 'training',
    confidence: 81,
    integrity: 89.2,
    rows: 1124000,
    params: '3.4B',
    size: '6.8 GB',
    scrape_source: 'stream://psychnet/affect',
    scrape_date: '2026-04-27T03:52:00Z',
    last_sync: '12m ago',
    tags: ['Affect', 'Real-time', 'Streaming'],
    linked: 156,
    sigil: 'pulse',
    palette: ['#10d98a', '#00f0ff'],
    bars: [
      { l: 'Latency', v: 94, c: 'green' },
      { l: 'Recall', v: 78, c: 'cyan' },
      { l: 'Stability', v: 71, c: 'amber' },
    ],
    summary: 'Streaming affect kernel that classifies emotional state at 30Hz. Currently mid-epoch; expect drift until 2026-05-03.',
    spark: [62, 65, 68, 72, 74, 76, 78, 79, 80, 81, 81],
  },
  {
    id: 'mdl-archetype-synth',
    kind: 'model', subkind: 'synthesis',
    name: 'Archetype Loom',
    tagline: 'Generative character archetype synth',
    faction: 'Vanguard',
    status: 'active',
    confidence: 90,
    integrity: 95.3,
    rows: 248000,
    params: '8.6B',
    size: '17 GB',
    scrape_source: 'derived://prism/archetypes',
    scrape_date: '2026-04-24T14:00:00Z',
    last_sync: '2d ago',
    tags: ['Generative', 'Archetype', 'Synth'],
    linked: 96,
    sigil: 'loom',
    palette: ['#9b5cff', '#fbbf24'],
    bars: [
      { l: 'Coherence', v: 92, c: 'purple' },
      { l: 'Novelty', v: 78, c: 'gold' },
      { l: 'Depth', v: 86, c: 'cyan' },
    ],
    summary: 'A generative loom that weaves new character archetypes from latent traits. Outputs feed directly into the Character Library.',
    spark: [82, 84, 85, 86, 88, 89, 89, 90, 90, 90, 90],
  },
  {
    id: 'mdl-memory-shard',
    kind: 'model', subkind: 'memory',
    name: 'Mnemonic Shardspace',
    tagline: 'Long-form episodic memory store',
    faction: 'Neutrals',
    status: 'active',
    confidence: 87,
    integrity: 94.0,
    rows: 3128000,
    params: '512M',
    size: '12.4 GB',
    scrape_source: 'derived://prism/memories',
    scrape_date: '2026-04-26T19:14:00Z',
    last_sync: '6h ago',
    tags: ['Memory', 'Episodic', 'Long-form'],
    linked: 2048,
    sigil: 'crystal',
    palette: ['#e040fb', '#9b5cff'],
    bars: [
      { l: 'Recall', v: 88, c: 'magenta' },
      { l: 'Salience', v: 84, c: 'purple' },
      { l: 'Decay', v: 22, c: 'amber' },
    ],
    summary: 'A 3.1M-shard episodic store. Each shard is a discrete memory with salience, decay, and emotional charge — the substrate for continuity.',
    spark: [76, 78, 80, 82, 83, 84, 85, 86, 86, 87, 87],
  },

  // ── CHARACTER ENTITIES ────────────────────────────────────────
  {
    id: 'chr-lira-velmont',
    kind: 'character', subkind: 'protagonist',
    name: 'Lira Velmont',
    tagline: 'The Strategist',
    faction: 'Vanguard',
    status: 'active',
    confidence: 99,
    integrity: 99.2,
    scrape_source: 'native://prism/characters',
    scrape_date: '2026-04-27T18:00:00Z',
    last_sync: '2h ago',
    tags: ['Strategist', 'Protagonist', 'Empath'],
    linked: 47,
    sigil: 'portrait',
    palette: ['#9b5cff', '#e040fb'],
    bars: [
      { l: 'Trust', v: 87, c: 'purple' },
      { l: 'Affection', v: 72, c: 'magenta' },
      { l: 'Resistance', v: 22, c: 'amber' },
    ],
    summary: 'A natural leader with exceptional interpersonal skills and a vision for the greater good. Lira sees patterns others miss and turns complexity into clarity.',
    spark: [82, 84, 85, 86, 87, 88, 88, 88, 87, 87, 87],
  },
  {
    id: 'chr-darius-nightfall',
    kind: 'character', subkind: 'ally',
    name: 'Darius Nightfall',
    tagline: 'The Maverick',
    faction: 'Allies',
    status: 'active',
    confidence: 94,
    integrity: 96.8,
    scrape_source: 'native://prism/characters',
    scrape_date: '2026-04-26T11:32:00Z',
    last_sync: '11h ago',
    tags: ['Maverick', 'Independent', 'Tactical'],
    linked: 38,
    sigil: 'portrait',
    palette: ['#00f0ff', '#9b5cff'],
    bars: [
      { l: 'Trust', v: 60, c: 'cyan' },
      { l: 'Affection', v: 45, c: 'purple' },
      { l: 'Resistance', v: 70, c: 'gold' },
    ],
    summary: 'An independent operator who plays his own game. Useful, dangerous, rarely both at once.',
    spark: [55, 58, 60, 62, 60, 58, 60, 62, 60, 60, 60],
  },
  {
    id: 'chr-shadow',
    kind: 'character', subkind: 'adversary',
    name: 'Shadow',
    tagline: 'The Mirror',
    faction: 'Adversaries',
    status: 'active',
    confidence: 71,
    integrity: 88.4,
    scrape_source: 'native://prism/characters',
    scrape_date: '2026-04-21T22:18:00Z',
    last_sync: '6d ago',
    tags: ['Adversary', 'Mirror', 'Unknown'],
    linked: 14,
    sigil: 'portrait',
    palette: ['#ff2d75', '#9b5cff'],
    bars: [
      { l: 'Trust', v: 25, c: 'red' },
      { l: 'Suspicion', v: 70, c: 'amber' },
      { l: 'Resistance', v: 85, c: 'red' },
    ],
    summary: 'Reflects what you are. Rarely speaks. Always listening. Whatever Shadow is, it learned it from you.',
    spark: [30, 28, 26, 25, 22, 24, 25, 24, 25, 26, 25],
  },

  // ── DATASETS ──────────────────────────────────────────────────
  {
    id: 'ds-dialogue-corpus',
    kind: 'dataset', subkind: 'corpus',
    name: 'Tongues-of-Atlas',
    tagline: 'Multilingual roleplay dialogue corpus',
    faction: 'Vanguard',
    status: 'active',
    confidence: 95,
    integrity: 97.8,
    rows: 24800000,
    size: '88 GB',
    scrape_source: 'mirror://atlas/tongues',
    scrape_date: '2026-04-18T09:42:00Z',
    last_sync: '9d ago',
    tags: ['Dialogue', '64 langs', 'Roleplay'],
    linked: 612,
    sigil: 'columns',
    palette: ['#00f0ff', '#10d98a'],
    bars: [
      { l: 'Coverage', v: 95, c: 'cyan' },
      { l: 'Cleanliness', v: 88, c: 'green' },
      { l: 'Diversity', v: 92, c: 'purple' },
    ],
    summary: '24.8M utterances across 64 languages. Filtered for in-character dialogue, annotated for affect, register, and intent.',
    spark: [85, 87, 88, 90, 91, 92, 93, 94, 94, 95, 95],
  },
  {
    id: 'ds-trait-norms',
    kind: 'dataset', subkind: 'norms',
    name: 'Norms-of-the-Compass',
    tagline: 'Cross-population trait norm tables',
    faction: 'Allies',
    status: 'active',
    confidence: 91,
    integrity: 95.6,
    rows: 482000,
    size: '912 MB',
    scrape_source: 'mirror://compass/norms',
    scrape_date: '2026-04-23T13:10:00Z',
    last_sync: '5d ago',
    tags: ['Norms', 'Population', 'Calibration'],
    linked: 204,
    sigil: 'columns',
    palette: ['#fbbf24', '#9b5cff'],
    bars: [
      { l: 'Pop. Coverage', v: 90, c: 'gold' },
      { l: 'Calibration', v: 92, c: 'purple' },
      { l: 'Recency', v: 78, c: 'cyan' },
    ],
    summary: 'Trait normalization tables across 38 populations. Used to calibrate raw scores into z-distributed percentiles.',
    spark: [82, 84, 85, 87, 88, 89, 90, 91, 91, 91, 91],
  },

  // ── MEMORY SHARDS ─────────────────────────────────────────────
  {
    id: 'mem-mission-briefing-1024',
    kind: 'memory', subkind: 'mission',
    name: 'Briefing #1024',
    tagline: 'The pieces are moving',
    faction: 'Vanguard',
    status: 'archived',
    confidence: 99,
    integrity: 100,
    scrape_source: 'session://prism/2026-04-27',
    scrape_date: '2026-04-27T14:02:00Z',
    last_sync: '2h ago',
    tags: ['Mission', 'Lira', 'High Impact'],
    linked: 12,
    sigil: 'crystal',
    palette: ['#9b5cff', '#e040fb'],
    bars: [
      { l: 'Salience', v: 94, c: 'purple' },
      { l: 'Charge', v: 82, c: 'magenta' },
      { l: 'Decay', v: 4, c: 'green' },
    ],
    summary: '"The pieces are moving. Stay ready." — Lira, before the Vanguard convened. Tagged: high impact, low decay, anchor.',
    spark: [99, 98, 97, 96, 95, 95, 94, 94, 94, 94, 94],
  },
  {
    id: 'mem-fracture-night',
    kind: 'memory', subkind: 'event',
    name: 'The Fracture Night',
    tagline: 'When Shadow first answered',
    faction: 'Adversaries',
    status: 'sealed',
    confidence: 62,
    integrity: 78.4,
    scrape_source: 'session://prism/2026-03-09',
    scrape_date: '2026-03-09T03:14:00Z',
    last_sync: '49d ago',
    tags: ['Event', 'Sealed', 'Origin'],
    linked: 28,
    sigil: 'crystal',
    palette: ['#ff2d75', '#9b5cff'],
    bars: [
      { l: 'Salience', v: 88, c: 'red' },
      { l: 'Charge', v: 96, c: 'magenta' },
      { l: 'Decay', v: 34, c: 'amber' },
    ],
    summary: 'A sealed memory shard. Access requires Vanguard quorum. The night the mirror answered back.',
    spark: [70, 68, 66, 64, 62, 60, 62, 62, 62, 62, 62],
  },

  // ── VOICE PROFILES ────────────────────────────────────────────
  {
    id: 'vox-lira-001',
    kind: 'voice', subkind: 'character',
    name: 'Lira / Resonance Lock',
    tagline: 'Warm contralto · measured cadence',
    faction: 'Vanguard',
    status: 'active',
    confidence: 96,
    integrity: 98.0,
    size: '142 MB',
    scrape_source: 'derived://prism/voices/lira',
    scrape_date: '2026-04-25T10:00:00Z',
    last_sync: '3d ago',
    tags: ['Contralto', 'Warm', 'Strategist'],
    linked: 8,
    sigil: 'wave',
    palette: ['#9b5cff', '#00f0ff'],
    bars: [
      { l: 'Timbre Lock', v: 96, c: 'purple' },
      { l: 'Affect Range', v: 82, c: 'cyan' },
      { l: 'Cadence', v: 88, c: 'magenta' },
    ],
    summary: 'A locked voice fingerprint for Lira Velmont. Pairs with AffectKernel for real-time prosodic modulation.',
    spark: [88, 90, 92, 93, 94, 95, 95, 96, 96, 96, 96],
  },
  {
    id: 'vox-shadow-veil',
    kind: 'voice', subkind: 'character',
    name: 'Shadow / Veil',
    tagline: 'Whisper-band · sub-300Hz floor',
    faction: 'Adversaries',
    status: 'restricted',
    confidence: 74,
    integrity: 86.0,
    size: '96 MB',
    scrape_source: 'derived://prism/voices/shadow',
    scrape_date: '2026-04-22T01:42:00Z',
    last_sync: '6d ago',
    tags: ['Whisper', 'Restricted', 'Sub-band'],
    linked: 3,
    sigil: 'wave',
    palette: ['#ff2d75', '#9b5cff'],
    bars: [
      { l: 'Timbre Lock', v: 74, c: 'red' },
      { l: 'Affect Range', v: 48, c: 'amber' },
      { l: 'Cadence', v: 60, c: 'purple' },
    ],
    summary: 'Restricted profile. Floor frequencies suppressed below 280Hz. Use only with Vanguard escort.',
    spark: [72, 73, 74, 74, 75, 74, 74, 74, 74, 74, 74],
  },

  // ── ARCHETYPE TEMPLATES ───────────────────────────────────────
  {
    id: 'arc-strategist',
    kind: 'archetype', subkind: 'template',
    name: 'The Strategist',
    tagline: 'Pattern → leverage → outcome',
    faction: 'Vanguard',
    status: 'active',
    confidence: 95,
    integrity: 97.4,
    rows: 412,
    scrape_source: 'derived://prism/archetypes',
    scrape_date: '2026-04-20T08:30:00Z',
    last_sync: '8d ago',
    tags: ['Cognitive', 'Long-arc', 'Lead'],
    linked: 96,
    sigil: 'pentagon',
    palette: ['#9b5cff', '#fbbf24'],
    bars: [
      { l: 'Cognitive', v: 92, c: 'purple' },
      { l: 'Empathic', v: 78, c: 'gold' },
      { l: 'Volatile', v: 22, c: 'green' },
    ],
    summary: 'Long-horizon planner. Spends affection currency for trust currency. Rarely improvises but rarely needs to.',
    spark: [90, 91, 92, 92, 93, 94, 94, 95, 95, 95, 95],
  },
  {
    id: 'arc-catalyst',
    kind: 'archetype', subkind: 'template',
    name: 'The Catalyst',
    tagline: 'Disrupt → ignite → exit',
    faction: 'Neutrals',
    status: 'active',
    confidence: 89,
    integrity: 94.0,
    rows: 287,
    scrape_source: 'derived://prism/archetypes',
    scrape_date: '2026-04-19T18:14:00Z',
    last_sync: '9d ago',
    tags: ['Disruptive', 'Volatile', 'Energetic'],
    linked: 64,
    sigil: 'arc',
    palette: ['#e040fb', '#fbbf24'],
    bars: [
      { l: 'Cognitive', v: 78, c: 'magenta' },
      { l: 'Empathic', v: 64, c: 'gold' },
      { l: 'Volatile', v: 88, c: 'red' },
    ],
    summary: 'High-energy disruptor. Inserts chaos where the system has stalled. Burns hot, leaves room.',
    spark: [82, 84, 86, 87, 88, 88, 89, 89, 89, 89, 89],
  },

  // ── REPO FILES ────────────────────────────────────────────────
  {
    id: 'repo-prism-theme',
    kind: 'file', subkind: 'css',
    name: 'prism-theme.css',
    tagline: 'Shared design tokens',
    faction: 'Vanguard',
    status: 'active',
    confidence: 100,
    integrity: 100,
    size: '7.7 KB',
    scrape_source: 'repo://dashboard/prism-theme.css',
    scrape_date: '2026-04-26T22:00:00Z',
    last_sync: '6h ago',
    tags: ['CSS', 'Tokens', 'Theme'],
    linked: 12,
    sigil: 'file',
    palette: ['#00f0ff', '#9b5cff'],
    bars: [
      { l: 'Coverage', v: 100, c: 'cyan' },
      { l: 'Stability', v: 96, c: 'purple' },
      { l: 'Drift', v: 4, c: 'green' },
    ],
    summary: 'Canonical color, type, and radius tokens for every Prism surface. Imported by all dashboard cards.',
    spark: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
  },
  {
    id: 'repo-character-connector',
    kind: 'file', subkind: 'js',
    name: 'character-connector.js',
    tagline: 'Live character data bridge',
    faction: 'Allies',
    status: 'active',
    confidence: 98,
    integrity: 97.2,
    size: '14.2 KB',
    scrape_source: 'repo://character-connector.js',
    scrape_date: '2026-04-26T22:00:00Z',
    last_sync: '6h ago',
    tags: ['JS', 'Bridge', 'Live'],
    linked: 6,
    sigil: 'file',
    palette: ['#fbbf24', '#10d98a'],
    bars: [
      { l: 'Coverage', v: 98, c: 'gold' },
      { l: 'Stability', v: 94, c: 'green' },
      { l: 'Drift', v: 8, c: 'amber' },
    ],
    summary: 'Mediator between scraped character DBs and the Live Character intel surface. WebSocket fall-back to mock.',
    spark: [94, 95, 96, 97, 97, 98, 98, 98, 98, 98, 98],
  },
];

// Stable color map per kind — used for chips, sigils, headers
window.KIND_META = {
  model:     { label: 'Model',     glyph: '◇', accent: '#9b5cff' },
  character: { label: 'Character', glyph: '◈', accent: '#e040fb' },
  dataset:   { label: 'Dataset',   glyph: '⬡', accent: '#00f0ff' },
  memory:    { label: 'Memory',    glyph: '◉', accent: '#fbbf24' },
  voice:     { label: 'Voice',     glyph: '◎', accent: '#10d98a' },
  archetype: { label: 'Archetype', glyph: '✦', accent: '#ff8a1c' },
  file:      { label: 'File',      glyph: '▤', accent: '#6ad6ff' },
};

window.FACTION_META = {
  Vanguard:    { color: '#9b5cff' },
  Allies:      { color: '#10d98a' },
  Neutrals:    { color: '#fbbf24' },
  Adversaries: { color: '#ff2d75' },
};

window.BAR_COLOR = {
  purple:  '#9b5cff',
  cyan:    '#00f0ff',
  magenta: '#e040fb',
  green:   '#10d98a',
  gold:    '#fbbf24',
  amber:   '#ff8a1c',
  red:     '#ff2d75',
};
