import * as React from "react";
import { Button } from "./Button";

/**
 * Chromatic Hero — canonical token-driven, above-the-fold section.
 * Implements 03_components/hero-component.md. Every visual value maps to a
 * Chromatic token via Tailwind classes generated by scripts/build-tokens.mjs
 * (Design Law #1). No hardcoded colors, spacing, or radii.
 */
export interface HeroProps {
  badge?: string;
  /** Headline; the second line renders as a gradient sweep. */
  title: React.ReactNode;
  titleAccent?: React.ReactNode;
  subtitle?: React.ReactNode;
  primaryCta?: { label: string; href?: string; onClick?: () => void };
  ghostCta?: { label: string; href?: string; onClick?: () => void };
}

export function Hero({
  badge,
  title,
  titleAccent,
  subtitle,
  primaryCta,
  ghostCta,
}: HeroProps) {
  return (
    <section className="relative overflow-hidden bg-gradient-hero py-9 px-5">
      {/* Aurora / glow-edge overlay (Design Law #5 + #7). */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 bg-gradient-glowEdge motion-reduce:hidden"
      />
      <div className="relative mx-auto flex max-w-5xl flex-col items-start gap-5">
        {badge && (
          <span className="inline-flex items-center rounded-full border border-border-default bg-surface-default px-4 py-1 text-label uppercase tracking-wide text-text-secondary">
            {badge}
          </span>
        )}
        <h1 className="font-heading text-4xl font-bold text-text-primary glow-text">
          {title}
          {titleAccent && (
            <>
              <br />
              <span className="bg-gradient-accentSweep bg-clip-text text-transparent">
                {titleAccent}
              </span>
            </>
          )}
        </h1>
        {subtitle && (
          <p className="max-w-2xl font-body text-lg text-text-secondary">
            {subtitle}
          </p>
        )}
        {(primaryCta || ghostCta) && (
          <div className="flex flex-wrap gap-4">
            {primaryCta && (
              <Button variant="primary" href={primaryCta.href} onClick={primaryCta.onClick}>
                {primaryCta.label}
              </Button>
            )}
            {ghostCta && (
              <Button variant="ghost" href={ghostCta.href} onClick={ghostCta.onClick}>
                {ghostCta.label}
              </Button>
            )}
          </div>
        )}
      </div>
    </section>
  );
}

export default Hero;
