import * as React from "react";

/**
 * Chromatic Hero — canonical token-driven, above-the-fold section.
 * Implements 03_components/hero-component.md. Every visual value maps to a
 * Chromatic token via Tailwind classes generated by scripts/build-tokens.mjs
 * (Design Law #1). No hardcoded colors, spacing, or radii.
 */
export interface HeroProps {
  badge?: string;
  /** Headline; the second line renders as a gradient sweep. */
  title: React.ReactNode;
  titleAccent?: React.ReactNode;
  subtitle?: React.ReactNode;
  primaryCta?: { label: string; href?: string; onClick?: () => void };
  ghostCta?: { label: string; href?: string; onClick?: () => void };
}

function Cta({
  cta,
  variant,
}: {
  cta: NonNullable<HeroProps["primaryCta"]>;
  variant: "primary" | "ghost";
}) {
  const base =
    "inline-flex items-center justify-center px-5 py-3 rounded-md text-base font-medium transition duration-fast ease-easeOut focus-visible:outline-none focus-visible:shadow-glow-focus";
  const styles =
    variant === "primary"
      ? "bg-primary-600 text-text-primary hover:bg-primary-500 hover:shadow-glow-hover hover:-translate-y-px"
      : "border border-border-default text-text-secondary hover:bg-surface-default hover:text-text-primary hover:border-primary-700";
  const className = `${base} ${styles}`;
  return cta.href ? (
    <a href={cta.href} className={className}>
      {cta.label}
    </a>
  ) : (
    <button type="button" onClick={cta.onClick} className={className}>
      {cta.label}
    </button>
  );
}

export function Hero({
  badge,
  title,
  titleAccent,
  subtitle,
  primaryCta,
  ghostCta,
}: HeroProps) {
  return (
    <section className="relative overflow-hidden bg-gradient-hero py-9 px-5">
      {/* Aurora / glow-edge overlay (Design Law #5 + #7). */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 bg-gradient-glowEdge motion-reduce:hidden"
      />
      <div className="relative mx-auto flex max-w-5xl flex-col items-start gap-5">
        {badge && (
          <span className="inline-flex items-center rounded-full border border-border-default bg-surface-default px-4 py-1 text-label uppercase tracking-wide text-text-secondary">
            {badge}
          </span>
        )}
        <h1 className="font-heading text-4xl font-bold text-text-primary glow-text">
          {title}
          {titleAccent && (
            <>
              <br />
              <span className="bg-gradient-accentSweep bg-clip-text text-transparent">
                {titleAccent}
              </span>
            </>
          )}
        </h1>
        {subtitle && (
          <p className="max-w-2xl font-body text-lg text-text-secondary">
            {subtitle}
          </p>
        )}
        {(primaryCta || ghostCta) && (
          <div className="flex flex-wrap gap-4">
            {primaryCta && <Cta cta={primaryCta} variant="primary" />}
            {ghostCta && <Cta cta={ghostCta} variant="ghost" />}
          </div>
        )}
      </div>
    </section>
  );
}

export default Hero;
