#!/usr/bin/env node
/**
 * build-tokens.mjs — Chromatic Design Studios token pipeline.
 *
 * Single source of truth: 02_design_tokens/tokens.*.json.
 * Emits, for consumption by apps/web (and any Tailwind consumer):
 *   - apps/web/src/styles/chromatic-tokens.css  (CSS custom properties)
 *   - apps/web/src/styles/chromatic-theme.ts     (Tailwind theme.extend object)
 *
 * Design Law #1 (Token-Driven): every visual value references a token.
 * Run: node scripts/build-tokens.mjs   (or: npm run tokens)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_DIR = path.join(ROOT, '02_design_tokens');
const OUT_DIR = path.join(ROOT, 'apps', 'web', 'src', 'styles');

const read = (f) => JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, f), 'utf8'));
const colors = read('tokens.colors.json');
const spacing = read('tokens.spacing.json');
const typography = read('tokens.typography.json');
const motion = read('tokens.motion.json');
const glow = read('tokens.glow.json');

// ---- helpers ----------------------------------------------------------------
const cssVars = [];
const pushVar = (name, value) => cssVars.push(`  --${name}: ${value};`);

// Flatten a nested object into kebab CSS vars + collect a parallel tailwind map.
function walk(obj, prefix, onLeaf) {
  for (const [k, v] of Object.entries(obj)) {
    const key = `${prefix}-${k}`.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
    if (v && typeof v === 'object' && !Array.isArray(v)) walk(v, key, onLeaf);
    else onLeaf(key, v);
  }
}

// ---- COLORS -----------------------------------------------------------------
// background, surface, primary.*, accent.*, text.*, semantic.*, border.*,
// glow.* (rgba), gradient.* (strings).
const twColors = {};
for (const group of ['background', 'surface', 'text', 'border', 'semantic', 'glow']) {
  twColors[group] = {};
  walk(colors[group], `color-${group}`, (name, val) => {
    pushVar(name, val);
    // last segment is the tailwind key for this group
    const seg = name.split('-').pop();
    twColors[group][seg] = `var(--${name})`;
  });
}
for (const scale of ['primary', 'accent']) {
  twColors[scale] = {};
  for (const [step, val] of Object.entries(colors[scale])) {
    pushVar(`color-${scale}-${step}`, val);
    twColors[scale][step] = `var(--color-${scale}-${step})`;
  }
}
const twGradient = {};
for (const [k, val] of Object.entries(colors.gradient)) {
  pushVar(`gradient-${k}`, val);
  // keyed as `gradient-<k>` so the Tailwind utility reads bg-gradient-hero etc.
  twGradient[`gradient-${k}`] = `var(--gradient-${k})`;
}

// ---- SPACING + RADIUS -------------------------------------------------------
const twSpacing = {};
for (const [k, val] of Object.entries(spacing.scale)) {
  pushVar(`space-${k}`, val);
  twSpacing[k] = `var(--space-${k})`;
}
const twRadius = {};
for (const [k, val] of Object.entries(spacing.semantic.radius)) {
  pushVar(`radius-${k}`, val);
  twRadius[k] = `var(--radius-${k})`;
}

// ---- TYPOGRAPHY -------------------------------------------------------------
pushVar('font-heading', `'${typography.family.heading}', system-ui, sans-serif`);
pushVar('font-body', `'${typography.family.body}', system-ui, sans-serif`);
pushVar('font-mono', `'${typography.family.mono}', ui-monospace, monospace`);
const twFontFamily = {
  heading: ['var(--font-heading)'],
  body: ['var(--font-body)'],
  sans: ['var(--font-body)'],
  mono: ['var(--font-mono)'],
};
const twFontSize = {};
for (const [k, v] of Object.entries(typography.scale)) {
  pushVar(`text-${k}`, v.rem);
  twFontSize[k] = [v.rem, { lineHeight: String(v.lineHeight), letterSpacing: v.letterSpacing }];
}
const twFontWeight = {};
for (const [k, v] of Object.entries(typography.weight)) twFontWeight[k] = String(v);

// ---- MOTION -----------------------------------------------------------------
const twDuration = {};
for (const [k, val] of Object.entries(motion.duration)) {
  pushVar(`duration-${k}`, val);
  twDuration[k] = val;
}
const twEasing = {};
for (const [k, val] of Object.entries(motion.easing)) {
  pushVar(`ease-${k}`, val);
  twEasing[k] = val;
}

// ---- GLOW (box-shadow presets) ---------------------------------------------
const twBoxShadow = {};
for (const [k, val] of Object.entries(glow.preset)) {
  pushVar(`glow-${k}`, val);
  twBoxShadow[`glow-${k}`] = `var(--glow-${k})`;
}
for (const [k, val] of Object.entries(glow.intensity)) {
  pushVar(`glow-intensity-${k}`, val);
}

// ---- WRITE CSS --------------------------------------------------------------
const cssOut = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Source of truth: 02_design_tokens/tokens.*.json
 */
:root {
${cssVars.join('\n')}
}
`;

// ---- WRITE TAILWIND THEME ---------------------------------------------------
const theme = {
  colors: { ...twColors, transparent: 'transparent', current: 'currentColor' },
  spacing: twSpacing,
  borderRadius: twRadius,
  fontFamily: twFontFamily,
  fontSize: twFontSize,
  fontWeight: twFontWeight,
  transitionDuration: twDuration,
  transitionTimingFunction: twEasing,
  boxShadow: twBoxShadow,
  backgroundImage: twGradient,
};
const tsOut = `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source of truth: 02_design_tokens/tokens.*.json
import type { Config } from 'tailwindcss';

export const chromaticTheme: Config['theme'] = {
  extend: ${JSON.stringify(theme, null, 2)},
};

export default chromaticTheme;
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'chromatic-tokens.css'), cssOut);
fs.writeFileSync(path.join(OUT_DIR, 'chromatic-theme.ts'), tsOut);

console.log(`[build-tokens] wrote ${cssVars.length} CSS vars + Tailwind theme to apps/web/src/styles/`);
